### ISSUE TITLE
issue in  conn.Connect()

### ISSUE THREAD

**Issue by Mohammedsalah19** [huysentruitw/SapNwRfc#1]
System.EntryPointNotFoundException: 'Unable to find an entry point named 'RfcOpenConnection' in DLL 'sapnwrfc'.'

**Comment by huysentruitw** [comment]
are you using version 7.50 of the SAP NetWeaver SDK?

**Comment by Mohammedsalah19** [comment]
how check my version?

**Comment by Mohammedsalah19** [comment]
how check my version?

**Comment by huysentruitw** [comment]
Can you right-click the sapnwrfc.dll file and go to the 'Details' tab?

![image](https://user-images.githubusercontent.com/4618744/78883326-a957c100-7a59-11ea-81a1-a6ed8fc0ed7e.png)

**Comment by Mohammedsalah19** [comment]
no i have not this version... can i upload dll as reference in my project is it enough ?

**Comment by huysentruitw** [comment]
I'm afraid the SAP license does not allow me or you to share any of their DLL's, they need to be officially downloaded by a user with access to the SAP support portal: https://launchpad.support.sap.com/#/notes/2573790

**Comment by Mohammedsalah19** [comment]
DAMN.. i haven't access  "D

**Comment by huysentruitw** [comment]
If you do get the libraries somehow, the DLL's are in the `\nwrfcsdk\lib` subfolder in the .zip archive.

**Comment by huysentruitw** [comment]
@Mohammedsalah19 I made a stupid mistake while releasing this library. The generated DLL had the same name as the DLL from SAP, so that's why your application picked the wrong one and you got the `'Unable to find an entry point named 'RfcOpenConnection' in DLL 'sapnwrfc'` error 🤦

**Comment by huysentruitw** [comment]
Please retest with version 1.0.0.49 of this package. I would clean your projects `bin\` and `obj\` folder once and rebuild everything. 

Can you let me know how it goes?

**Comment by huysentruitw** [comment]
I'll close this issue for now as it has been identified and fixed at my end. Feel free to reopen if it isn't fixed for you.
