### ISSUE TITLE
"Type 'System.String' does not have a default constructor (Parameter 'type')"

### ISSUE THREAD

**Issue by GustavoDamasceno** [huysentruitw/SapNwRfc#103]
I am trying to send data to a table from an RFC. Here is the table structure:

![image](https://github.com/user-attachments/assets/d776cea7-f983-4aa3-8956-7c26936dc628)
![image](https://github.com/user-attachments/assets/79afabfb-2c1b-42bf-8d1f-de8d26dc61da)

To send the data, I am creating this algorithm:

```csharp

var parameters = new SapFuncionParameters
{
    table = new[]
    {
        new ZSDS_EASYP_MSG
        {
            message = mensagem
        }
    }
};

string connectionString = sapConfig.SapconnectionString(ConfigurationManager.AppSettings["Ambiente"].ToString());
using var connection = new SapConnection(connectionString);

try
{
    connection.Connect();

    using var someFunction = connection.CreateFunction("ZRFC_EASY_PALLET_04");
    var result = someFunction.Invoke<string>(new SapFuncionParameters
    {
        table = parameters.table
    });

    Console.WriteLine("Log salvo no SAP com sucesso.");

}
catch (Exception ex)
{

    throw ex;
}

```
And since it is a table structure, I created the following classes for the parameter I want to send to SAP.

```csharp

public class SapFuncionParameters
{
    [SapName("T_MESSAGE")]
    public ZSDS_EASYP_MSG[] table { get; set; }
}

public class ZSDS_EASYP_MSG
{
    [SapName("MESSAGE")]
    public string message { get; set; }
}

```

However, I am not successful. I have tried converting it to a list instead of an array, but without success.

In the old SAP NCO with .NET Framework support, I used to do it like this:

```csharp

RfcDestination dest = GetRepository("ITGViagem");
RfcRepository repo = dest.Repository;
IRfcFunction fReadTable = repo.CreateFunction("ZRFC_EASY_PALLET_04");
var dtImportCli = fReadTable.GetTable("T_MESSAGE");
dtImportCli.Append();

 //dtImportCli.Append();
id = id.PadLeft(10, '0'); ;
msg = msg;

string mensagem = id + " | " + msg;
dtImportCli.SetValue("MESSAGE", mensagem);

fReadTable.SetValue("T_MESSAGE", dtImportCli);
fReadTable.Invoke(dest);

```

Is it possible to do the same for SAP NWRFC?

**Comment by tom-j-irvine** [comment]
It looks like you are asking it to respond with a string:

![image](https://github.com/user-attachments/assets/87a1cc40-e8be-44ae-82ef-cbf855982b4f)

If you don't require a response, you would invoke the function like this:
https://github.com/huysentruitw/SapNwRfc?tab=readme-ov-file#call-function-with-input-parameters-but-no-output-parameters

Otherwise, you need to give it an appropriate class for the output.

**Comment by GustavoDamasceno** [comment]
Thanks
