### ISSUE TITLE
Add R3NAME as Sap connection parameter

### ISSUE THREAD

**Issue by niki-funky** [huysentruitw/SapNwRfc#12]
I have SAP system which uses R3NAME as connection parameter. Can you add this to the list of parameters. 
Another problem I have is the speed of the code. There is a RFC function that returns(10000 rows) 2 tables with more then 50 properties in each table and it takes more then 30 seconds to process the result. 
Nice project. Keep up the good work

**Comment by huysentruitw** [comment]
Hi, thanks for reaching out.

I have added the R3NAME parameter and it will be available in version 1.0.0.63.

As for the bad performance, I don't have a dataset that large to do some tests. Are you familiar with Performance Profiler in Visual Studio? Perhaps you could do some profiling and send me the results?

I have seen in the past that even calling a simple function in SAP is slow, but I would like to know if the C# wrapper code could be optimized or if we're bumping against a limitation of the native SAP NetWeaver RFC libraries.

**Comment by niki-funky** [comment]
https://drive.google.com/file/d/1WsWIFoSLI5aKn8k3wJCSnwJey62aldU_/view?usp=sharing
here is the link to a profiler report

**Comment by huysentruitw** [comment]
As expected, the CPU is spending ~96% of its time in the native RfcGetString function. Do you know the RFCTYPE of the text fields you're querying? Are those RFCTYPE_CHAR or RFCTYPE_STRING or other?

I wonder if calling RfcGetChars with a fixed buffer size would be faster than RfcGetString.

An other thing I have in mind is, trying to reduce the calls to RfcGetString in half by passing in a large enough buffer (for most cases) to the first call inside https://github.com/huysentruitw/SapNwRfc/blob/master/src/SapNwRfc/Internal/Fields/StringField.cs#L30

This way, for most cases, we wouldn't have to call RfcGetString twice per field.

**Comment by niki-funky** [comment]
Most of the fields are of type CHAR.

**Comment by huysentruitw** [comment]
Hi Niki, in version 1.0.0.64 (currently building), I've added support for `char[]` to RFCTYPE_CHAR conversions. Can you please convert the CHAR fields from `string` to `char[]` and add a `[SapBufferLength(<length>)]` attribute to those fields?

Converting `char[]` to a string needs some additional code, but I'm interested in any performance different you'd see.

**Comment by niki-funky** [comment]
I'll check the new version when I have some free time.
Great work

**Comment by huysentruitw** [comment]
@niki-funky any update from your end?

**Comment by niki-funky** [comment]
I did not check the new version. I hope this week I'll have time to test it.

**Comment by huysentruitw** [comment]
Closing as this should have been fixed.
