### ISSUE TITLE
field 'VBELN' not found

### ISSUE THREAD

**Issue by panzhangguo** [huysentruitw/SapNwRfc#18]
RFC_INVALID_PARAMETER with message: field 'VBELN' not found

**Comment by huysentruitw** [comment]
I'm afraid there is not enough context for me. Can you please add more information?

**Comment by panzhangguo** [comment]
> I'm afraid there is not enough context for me. Can you please add more information?

 I got the wrong IP address for sap...so......sorry

**Comment by huysentruitw** [comment]
No problem, do you have it working now?
