### ISSUE TITLE
'sapnwrfc' DLL Cannot Load

### ISSUE THREAD

**Issue by karakaplankhan** [huysentruitw/SapNwRfc#19]
Hi. I have been working with this library for months. There was no problem until today. I get `Unable to load DLL 'sapnwrfc' or one of its dependencies: The specified module could not be found. (0x8007007E)` error whenever I try to run my application.

I downloaded correspending dlls from official website of SAP than unzipped them to a folder. Then I added path of this folder to Path of Windows Environment Variables. Like I said, my application was running smoothly until today. What should I do?

**Comment by huysentruitw** [comment]
Hi, thank you for using this library. Can you tell me a bit more about your environment?

* Which OS and OS version are you using? Could it be OS updates?
* Did you update this NuGet package or anything else?
* Which .NET verison are you using?
* What type of application (ASP.NET Core, Console app)?
* etc...

**Comment by shiroi-tora** [comment]
* Microsoft Windows 10 Enterprise 10.0.17763 N/A Build 17763
* I didn't update the packege, but code didn't worked so I thought I should update it. 
* .NET Core 3.1 
* I used it in a class library but the main project is a web application.

**Comment by RickGanKL** [comment]
@karakaplankhan Please check the following settings
![image](https://user-images.githubusercontent.com/42196505/105112748-9d2b8480-5afe-11eb-90ef-0d6e361ec92a.png)
