### ISSUE TITLE
Read results  from RfcFunction with  no parameters

### ISSUE THREAD

**Issue by NetCoreUser-Design** [huysentruitw/SapNwRfc#2]
How can we read the results returned by the RfcFunction 

Call function without input or output parameters

using var someFunction = connection.CreateFunction("BAPI_SOME_FUNCTION_NAME");
someFunction.Invoke();

**Comment by huysentruitw** [comment]
Hi,

when you are interested in the result, you need to create an output type (or structure) that mimics the structure you'd get back from the BAPI function. 

E.g.:

```C#
class SomeFunctionResult
{
    [SapName("RES_ABC")]
    public string Abc { get; set; }

    [SapName("RES_ITEMS")]
    public SomeFunctionResultItem[] Items { get; set; }
}

class SomeFunctionResultItem
{
    [SapName("ITM_NAME")]
    public string Name { get; set; }
}

using var someFunction = connection.CreateFunction("BAPI_SOME_FUNCTION_NAME");
var result = someFunction.Invoke<SomeFunctionResult>();
```

If you have troubles converting the BAPI structure to C# object structure, you can post it here so I can help.

**Comment by huysentruitw** [comment]
Ping @NetCoreUser-Design. Were you able to fix the issue?

**Comment by huysentruitw** [comment]
Closing this for now. Feel free to re-open in case of feedback. Thanks.
