### ISSUE TITLE
Add more information to the SapException

### ISSUE THREAD

**Issue by jwienekamp** [huysentruitw/SapNwRfc#20]
The `SapException`-Exception only includes the error message mixed with other text in the `Message` property. There is currently no way to read the raw exception message besides manually removing the other text.

An example `Message` currently looks like this: `SAP RFC Error: RFC_ABAP_RUNTIME_FAILURE with message: Invalid username.`.

Wouldn't it be helpful if the rfc error and the message are added to the `SapException` object? Or any other way to grab the raw message and/or the rfc error?

**Comment by huysentruitw** [comment]
Thanks for your request. It totally makes sense to have more information on the `SapException` object itself.

One thing I want to discuss is how you think we can meet your needs while still keeping `RfcErrorCode` and `RfcErrorInfo` internal.

The string properties from `RfcErrorInfo` could easily be mapped onto the exception itself, however, how do would you like the enums `RfcResultCode` and `RfcErrorGroup` to be mapped? As a string, number or other enum?

**Comment by jwienekamp** [comment]
In my opinion the best way would actually be an enum, with which an easy comparison would be possible. A string representation seems possible too, you just have to manually match the values then.

Is there a reason why you would like to keep the enums internal only?

**Comment by huysentruitw** [comment]
The enums are currently following the SAP specification and naming, which does not match with most naming conventions used in C#. So I will create new enums and map them.

**Comment by huysentruitw** [comment]
The enums are currently following the SAP specification and naming, which does not match with most naming conventions used in C#. So I will create new enums and map them, I guess 🙂

**Comment by huysentruitw** [comment]
Would [this](https://github.com/huysentruitw/SapNwRfc/pull/21) be useful?

**Comment by jwienekamp** [comment]
Yea, that seems to include everything needed. Looks good to me.
