### ISSUE TITLE
I used this to successfully connect to sap. but...

### ISSUE THREAD

**Issue by zhouren6** [huysentruitw/SapNwRfc#23]
I Used this link function  
https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table
Get the data returned by SAP  but

SAP returns the table as multiple rows,  one row is received
If sap has multiple rows, return to the last row

----------------------------code show as below----------------

 public class Output
        {
            [SapName("POITEMS ")]
            public POITEMSItem[] POITEMS { get; set; }
        }

   var result = Function.Invoke< Output >(Input);

---------------------------------------------------

**Comment by zhouren6** [comment]
var result = Function.Invoke< ff >(Input);

**Comment by huysentruitw** [comment]
Let me see if I understand your question correctly: so the array `POITEMS` only contains a single row (the last one), even though there should be multiple rows, correct?

**Comment by huysentruitw** [comment]
I have now incorporated [this change](https://github.com/huysentruitw/SapNwRfc/commit/e211f311667da117678be889a6ebfd3bacb01e06) made by @jwienekamp that should fix this issue. Version 1.0.0.78 of SapNwRfc should contain this fix, so please try again.

**Comment by huysentruitw** [comment]
Please reopen if v1.0.0.78+ hasn't fixed your issue. Regards.
