### ISSUE TITLE
When the table is both import and export parameters, the exported table has only the last data

### ISSUE THREAD

**Issue by Qiulin-Git** [huysentruitw/SapNwRfc#24]
`  public class SapFunctionInPut
    {

        [SapName("IV_COMMIT")]
        public string InPut{ get; set; }

        [SapName("IT_WERKS")]
        public SapFunction_IT_WERKS_ResultItem[] ItWerks { get; set; }

    }

    public class SapFunctionResult
    {
 
        [SapName("EV_RETURN")]
        public string ResultOut { get; set; }

        [SapName("IT_WERKS")]
        public SapFunction_IT_WERKS_ResultItem[] ItWerks { get; set; }

    }

  public ActionLogController(ISapPooledConnection connection)
        {
            _connection = connection;

            List<SapFunction_IT_WERKS_ResultItem> list = new List<SapFunction_IT_WERKS_ResultItem>();
            list.Add(new SapFunction_IT_WERKS_ResultItem {  Bukrs="8200",  Werks="8200" });
            list.Add(new SapFunction_IT_WERKS_ResultItem { Bukrs = "8200", Werks = "8210" });
            list.Add(new SapFunction_IT_WERKS_ResultItem { Bukrs = "8200", Werks = "8220" });

            SapFunction_IT_WERKS_ResultItem[] array = list.ToArray();
            
            var a =  _connection.InvokeFunction<SapFunctionResult>("ZFM_SMBG_GD"
                , new SapFunctionInPut
                {
                    InPut = "",
                    ItWerks = array
                  
                })
           
           ;

        }

`

**Comment by huysentruitw** [comment]
Related to #23 .

I have now incorporated [this change](https://github.com/huysentruitw/SapNwRfc/commit/e211f311667da117678be889a6ebfd3bacb01e06) made by @jwienekamp that should fix this issue. Version 1.0.0.78 of SapNwRfc will contain this fix, so please try again with v1.0.0.78 (or up) and report back please.
