### ISSUE TITLE
Switch to github actions

### ISSUE THREAD

**Issue by huysentruitw** [huysentruitw/SapNwRfc#25]

**Comment by t3643797** [comment]
with version greater than 1.0.0.76, when the RFCTYPE_TABLE is empty, an error will be reported。eg:
SapNwRfc.Exceptions.SapException:“SAP RFC Error: RFC_TABLE_MOVE_BOF with message: No first row”

**Comment by campersau** [comment]
I have started with it here https://github.com/campersau/SapNwRfc/commit/5995c42a0c7f229cd2b7eea2c37871cfc7b875ce
If you want you can take it as a starting point or let me know if I should create a PR with it.

**Comment by huysentruitw** [comment]
Moved to github actions since v1.1
