### ISSUE TITLE
Cannot resolve 'System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Hosting.IHostedService]' from root provider because it requires scoped service 'SapNwRfc.Pooling.ISapPooledConnection'.”

### ISSUE THREAD

**Issue by Qiulin-Git** [huysentruitw/SapNwRfc#27]
startup.cs
`services.AddTransient<Microsoft.Extensions.Hosting.IHostedService, Job.TestJob>();`

Timed task
` public class TestJob : BackgroundService
{

        private readonly ISapPooledConnection _connection;
        private readonly ILogger<TestJob> _logger;

        public TestJob(ILogger<TestJob> logger , ISapPooledConnection connection)
        {
            _logger = logger;
            _connection = connection;
        }
}`

**Comment by huysentruitw** [comment]
You'll probably have to change the registration of ISapPooledConnection from

```
services.AddScoped<ISapPooledConnection, SapPooledConnection>();
```

to

```
services.AddTransient<ISapPooledConnection, SapPooledConnection>();
```
