### ISSUE TITLE
Providing Dynamic Property Name

### ISSUE THREAD

**Issue by ongun23** [huysentruitw/SapNwRfc#3]
Can the developer provide a dynamic SAP field name like below for the Contract class?

```csharp
using System;
using System.Configuration;
using System.Reflection;

namespace SapNwRfc
{
    /// <summary>
    /// Attribute used to set the real SAP RFC property name of a property.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class SapNameAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SapNameAttribute"/> class.
        /// </summary>
        /// <param name="name">The SAP RFC property name.</param>
        /// <param name="config">Look in to the config file for this property value.</param>
        public SapNameAttribute(string name, bool config = false)
        {
            Name = name;
            if (config)
            {
                Name = ConfigurationManager.AppSettings[name];
            }
        }

        /// <summary>
        /// Gets the SAP RFC property name.
        /// </summary>
        public string Name { get; }
    }
}

**Comment by huysentruitw** [comment]
Do you mean specifying a field name at-runtime?

**Comment by huysentruitw** [comment]
If yes, I'd be glad to work out a way to make this work, so any suggestion on how you'd like it to work is more than welcome.

**Comment by huysentruitw** [comment]
Oops, didn't mean to close.

**Comment by ongun23** [comment]
Hey there,
A config file would be much easier for the property field change for many cases. Also, the class is sealed so inheritance is a bit tight.

**Comment by huysentruitw** [comment]
I had some time to think about this and I don't think it should be part of this library as feels like an opinionated way to store fieldnames in appsettings.json (we cannot support every single use-case of different ways of storing fieldnames). Additionally, it would mean an additional dependency on `System.Configuration`.

Anyway, I believe you should be able to do what you want to do and so I have removed the `sealed` modifier from the `SapNameAttribute` class, which enables you to do:

```C#
[AttributeUsage(AttributeTargets.Property)]
public class SapNameFromAppSettings : SapNameAttribute
{
    public SapNameFromConfigAttribute(string path)
        : base(ConfigurationManager.AppSettings[path])
    {
    }
}
```

**Comment by ongun23** [comment]
@huysentruitw Great job! I've been using this amazing library for one of a project and it was taking so much time to change property names because of the production and development environment. However, your recent development just nailed it! Great job, thanks!

**Comment by huysentruitw** [comment]
@ongun23 glad this small change helped you out. Feel free to star this project here on github, always appreciated ⭐
