### ISSUE TITLE
In-process hosting with IIS  Error:Could not open the lcu common library.  The following files must be in the path described by the environment variable "PATH": icuuc50.dll, icudt50.dll,icuin50.dll

### ISSUE THREAD

**Issue by Qiulin-Git** [huysentruitw/SapNwRfc#32]
![image](https://user-images.githubusercontent.com/53858121/119779165-f23b3500-befa-11eb-97a0-803ab3acd74a.png)

  I have placed the DLL in the project output folder，The Out-of-process hosting with IIS is running normally ,
But In-process hosting with IIS  Error:Could not open the lcu common library.  The following files must be in the path described by the environment variable "PATH": icuuc50.dll, icudt50.dll,icuin50.dll

**Comment by campersau** [comment]
What is the value of `Directory.GetCurrentDirectory()`?
Depending on the aspnet core version you might need to use this: https://github.com/dotnet/aspnetcore/issues/4206#issuecomment-445612167

**Comment by huysentruitw** [comment]
Great suggestion of @campersau to check the current directory. I have ran this as in-process under IIS without issues (by having the SAP dll's together with all other .NET dll's of the project on the server).

A workaround could be to place the SAP dll's in `C:\sap`, add `C:\sap` to the systems PATH variable and restart IIS.

**Comment by Qiulin-Git** [comment]
There is no problem registering the DLL into the system , But I want to call DLL directly in the project output folder
