### ISSUE TITLE
Unable to load shared library \'sapnwrfc\' or one of its dependencies. 

### ISSUE THREAD

**Issue by zhouren6** [huysentruitw/SapNwRfc#34]
HI,it runs well in window system, but it runs error in Linux system

I have already put the file, “SAP NetWeaver RFC Library 7.50 SDK,  under program directory”，but Linux still runned error.

----------------------------------Error Info--------------------------
Unable to load shared library \'sapnwrfc\' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsapnwrfc: cannot open shared object file: No such file or directory

**Comment by huysentruitw** [comment]
Have you figured out the issue yet?
