### ISSUE TITLE
Error when EnsureLibraryPresent

### ISSUE THREAD

**Issue by barnetlu** [huysentruitw/SapNwRfc#37]
I have copied all the necessary files to project root (sapnwrfc.dll, icuuc50.dll, icuin50.dll, icudt50.dll) but I still got error when I try to call this:

SapLibrary.EnsureLibraryPresent();
the error I got:

System.BadImageFormatException HResult=0x8007000B Message=An attempt was made to load a program with an incorrect format. (0x8007000B) Source=SapNwRfcDotNet StackTrace: at SapNwRfc.Internal.Interop.RfcInterop.RfcGetVersion(UInt32& majorVersion, UInt32& minorVersion, UInt32& patchLevel) at SapNwRfc.Internal.Interop.RfcInterop.GetVersion(UInt32& majorVersion, UInt32& minorVersion, UInt32& patchLevel) at SapNwRfc.SapLibrary.GetVersion() at SapNwRfc.SapLibrary.EnsureLibraryPresent()

I have tried to changed platform from Any CPU to x86 (then I got error from IIS Express), and x64 (the same behavior as Any CPU)

Do you have any tips how to handle it?

Thank you.

**Comment by barnetlu** [comment]
One additional note:

with .NET framework 4.7.2 it works but with Asp.Net Core 3.1 and .NET5 it does not...

**Comment by huysentruitw** [comment]
If it works for x86, it means you have the 32-bit SAP dll's in place. When you want to run it as x64, you need the 64-bit SAP dll's.

**Comment by barnetlu** [comment]
Yes, you are right. Even if the dll's  were in SysWOW64 they were not 64-bit... Thanks for great job!

**Comment by huysentruitw** [comment]
Don't hesitate to give this repo a star ⭐

Thanks you! 🎉

**Comment by EnesKartal** [comment]
> One additional note:
> 
> with .NET framework 4.7.2 it works but with .NET Core 2.1, 3.1 and .NET5 under x64 (x86 works) it does not...

You're best, thank you so much
