### ISSUE TITLE
Custom Output data binding

### ISSUE THREAD

**Issue by AlexAlexGoTO** [huysentruitw/SapNwRfc#48]
Hi, we have one issue, one of our customers using a bit different structure of result

Usually we are using:

```
public class SapColumn
{
     [SapName("WA")]
     public string Wa { get; set; }
}
```

But in our current situation one customer use LFT instead of WA, do you have any ideas how can I make that dynamic in this case ? By default use WA but if have special parameter then use LFT

Thanks.

**Comment by campersau** [comment]
You could try to use an interface and based on some condition use one or the other implementation like this:

```c#
public interface ISapResult
{
    string Field { get; set; }
}

public class SapResultWa : ISapResult
{
    [SapName("WA")]
    public string Field { get; set; }
}

public class SapResultLft : ISapResult
{
    [SapName("LFT")]
    public string Field { get; set; }
}



ISapResult result;
if (condition)
{
    result = fn.Invoke<SapResultWa>();
}
else
{
    result = fn.Invoke<SapResultLft>();
}

Console.WriteLine(result.Field);
````

**Comment by AlexAlexGoTO** [comment]
> You could try to use an interface and based on some condition use one or the other implementation like this:
> 
> ```cs
> public interface ISapResult
> {
>     string Field { get; set; }
> }
> 
> public class SapResultWa : ISapResult
> {
>     [SapName("WA")]
>     public string Field { get; set; }
> }
> 
> public class SapResultLft : ISapResult
> {
>     [SapName("LFT")]
>     public string Field { get; set; }
> }
> 
> 
> 
> ISapResult result;
> if (condition)
> {
>     result = fn.Invoke<SapResultWa>();
> }
> else
> {
>     result = fn.Invoke<SapResultLft>();
> }
> 
> Console.WriteLine(result.Field);
> ```

it's possible, but I need something dynamic, that I can use in runtime, because I don't know how many different cases like that can we have in future...

**Comment by AlexAlexGoTO** [comment]
We are using old sap library and that is pretty dynamic so we can use it like that
var fieldName = "**WA**"
target.CreateFunction("RFC_READ_TABLE").GetTable("DATA")[0].GetString(**fieldName**)

It would be cool if this library can handle result in more flexible way, not only by strongly Typed class

someFunction.Invoke<dynamic>(parameters) - doesn't work unfortunately(result is empty)

**Comment by campersau** [comment]
I started adding some metadata methods here https://github.com/huysentruitw/SapNwRfc/pull/44 which is the basis for enabling more dynamic scenarios like my prototype in https://github.com/huysentruitw/SapNwRfc/issues/36#issuecomment-885692636.
