### ISSUE TITLE
STRING_TABLE not supported

### ISSUE THREAD

**Issue by mrmorrandir** [huysentruitw/SapNwRfc#58]
While trying to invoke a custom method with the following metadata
```
IMPORTING
   VALUE(AUFNR) TYPE  SER05-PPAUFNR CHAR 12
EXPORTING
   VALUE(SERNR) TYPE  STRING_TABLE string[]
```
I get an error message telling me, that System.String has no default constructor - which is correct.

My response and request classes look like  this
```csharp
internal class FaufResponse
{
    public string[] SERNR { get; set; }
}

internal class FaufRequest
{
    public string AUFNR { get; set; }
}
```
The metadata for `SERNR` sais it's a `RFCTYPE_TABLE`. It's handled in the `BuildExtractExpressionForProperty` method by the `propertyInfo.PropertyType.IsArray` section. Later in the `TableField` the single rows are read via the `OutputMapper.Extract<T>()` function that handles this `string` as if it`s a reference type.

Does anyone have an idea how to support this `STRING_TABLE` type? Is it even supported in the RFC API?

Regards,
Andi

**Comment by tom-j-irvine** [comment]
I have done something similar and followed the readme documentation (the **Define Models with a Nested Table** section) to come up with something like the following - this works for me:
```
EXPORTING
  VALUE(TEST) TYPE CHAR50
  VALUE(DATA) TYPE STRING_TABLE
```

```
public class SomeResponse
{
    [SapName("TEST")
    public string Test { get; set; }

    [SapName("DATA")
    public DataLine[] Data { get; set; }
}

public class DataLine 
{ 
    [SapName("")
    public string Line { get; set; }
}
```

**Comment by mrmorrandir** [comment]
Wow! This is exactly what I needed! Thanks a lot!

I just played around with it and found some "default behavior" for this string arrays by using 

```csharp
else if (propertyInfo.PropertyType == typeof(string[]))
{
    extractMethod = typeof(StringTableField).GetMethod(nameof(StringTableField.Extract));
}
```

in `OutputMapper.BuildExtractExpressionForProperty` and a little helper / redirector class like

```csharp
internal class StringTableField
{
    public static TableField<string> Extract(RfcInterop interop, IntPtr dataHandle, string name)
    {
        TableField<StringTableElement> tableField = TableField<StringTableElement>.Extract<StringTableElement>(interop, dataHandle, name);
        return new TableField<string>(name, tableField.Value.Select(v => v.Data).ToArray());
    }
}
```

together with a class like the one you described:

```csharp
public class StringTableElement
{
    [SapName("")]
    public string Data { get; set; }

    public override string ToString()
    {
        return Data;
    }

    public static implicit operator string(StringTableElement element) => element.Data;
}
``` 

This way I don't have to refactor all my classes. I know it's not as generic as the rest - but it works great.
Thanks a lot for your help!
