### ISSUE TITLE
Connection pooling with 2 different SAP systems

### ISSUE THREAD

**Issue by Buffelstoot** [huysentruitw/SapNwRfc#66]
Hi,

Our application (Azure Function App) connects to 2 different SAP systems.
Is there a way to find out, maybe based on a SapConnectionParameter, which connection is in the SapConnectionPool?
Do I need to create a separate pool for each SAP system?

**Comment by tom-j-irvine** [comment]
Just another user commenting here, but I think you need two connection pools.  Even if you could discriminate between connections, you don't want to pull one out of the pool and then decide it isn't the one you want.  To me, a second pool is much cleaner anyway.

**Comment by Buffelstoot** [comment]
> Just another user commenting here, but I think you need two connection pools. Even if you could discriminate between connections, you don't want to pull one out of the pool and then decide it isn't the one you want. To me, a second pool is much cleaner anyway.

I've decided to go with 2 connection pools and it seems to be working as expected.
Thank you for your opinion.
