### ISSUE TITLE
(Question) C++ binaries ?

### ISSUE THREAD

**Issue by olsonperrensen** [huysentruitw/SapNwRfc#71]
Hi and thank you for your tool

I have been trying to get access to the NetWeaver SDK for a Python automation project for more than two months with my company's IT team having huge delays in between. 

Could you please provide me a direct or mirrored download link for the binaries so I can get started ? 

Thank you in advance!! 

Kind regards.

**Comment by jwienekamp** [comment]
The SAP NetWeaver SDK binaries are not publicly available and are also not allowed to be distributed in any way. 
However they can always be accessed and downloaded by your SAP Administrator on the SAP Service Marketplace. For download and installation instructions see [SAP Note 2573790](https://launchpad.support.sap.com/#/notes/2573790).

**Comment by huysentruitw** [comment]
Jens is correct, the only legal way is to download them from SAP servers directly for which you need to have authorized access.
