### ISSUE TITLE
How to fetch data from RFCTable

### ISSUE THREAD

**Issue by karthik090782** [huysentruitw/SapNwRfc#74]
I am calling a function whose metadata has multiple RFCTable and RFCStructures. I am not able to iterate through the RFCTable to get the values within the table. Can you please provide some instructions on how this can be achieved. Attached is the metadata information I am receiving from one of my function call.

[SAP_Function_Metadata.xlsx](https://github.com/huysentruitw/SapNwRfc/files/10049888/SAP_Function_Metadata.xlsx)

**Comment by tom-j-irvine** [comment]
The documentation is pretty clear on this.  These two sections cover mapping structures and tables:

https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-structure

https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table

Once you've correctly mapped the function to a model, iterating over the rows of the table is as simple as iterating over the array in your model that represents that table.

**Comment by karthik090782** [comment]
Thanks Tom, I will give it a try.

**Comment by karthik090782** [comment]
Thanks Tom, we are able to fetch data from tables now.
