### ISSUE TITLE
SERVER: Invalid parameter 'unsigned paramCount' was passed to the API.

### ISSUE THREAD

**Issue by basis100** [huysentruitw/SapNwRfc#76]
![image](https://user-images.githubusercontent.com/26346549/213606461-2f2f3bf7-1fd0-4d2c-9c93-4489dc5c8a03.png)

Dear huysentruitw:

I new bulid the winform program in VS2019, test the server model, then there was a error as follow:
  "**SAP RFC Error: RFC_INVALID_PARAMETER with message: Invalid parameter 'unsigned paramCount' was passed to the API** "

thanks a lot.

**Comment by tom-j-irvine** [comment]
One thing that looks odd in your server connection string is the `GWSERV` parameter.  For a system number `00`, I would expect this parameter to be `sapgw00` as opposed to `3300`.  That doesn't really match up with the error message you are getting, but I rarely trust SAP error messages anyway :).

**Comment by campersau** [comment]
Unfortunately the documentation was wrong, please use this as the server connection string:
`"GatewayHost=10.18.102.1; GatewayService=3300; ProgramId=JAMES888; RegistrationCount=1"`

I updated the README here: https://github.com/huysentruitw/SapNwRfc/pull/53/commits/b1ab618f5629645a72a41a39cce761d0be8cca87

**Comment by basis100** [comment]
Dear campersau：
I tested the new parameter name and the server mode connection worked。thanks.

I have another question: 
I want to make a configuration of the NCO program(adapter), but NCO function parameters must be defined by the class, I want to compile once, after the change of the function to use dynamic configuration, I do not know whether it can be achieved?
