### ISSUE TITLE
Using BAPI_XBP_JOB_START_ASAP doesn't start the job

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [huysentruitw/SapNwRfc#77]
Hi @huysentruitw and team

I have a requirement where I need to run an existing job, and wait for it to finish. As per the readme file, I have added the _SapNwRfc_ package and added the required _dlls_ as the project reference.

I'm able to set-up the connection as `.Connect() `and `.Ping() ` are returning true, but when I'm trying to run a job in SAP, it is not performing any action. 
I'm using the below code to trigger the Job.
```
ISapFunction something = connection.CreateFunction("BAPI_XBP_JOB_START_ASAP");
something.Invoke(new JobParameters
{
    JobName= "JOBNAME",
});
```

This doesn't throw any error but when I look at the client, no operation is performed as well even after multiple refresh.

Is this the right way to do it? or is there something else we need to add here?

**Comment by tom-j-irvine** [comment]
I think you probably need to try executing that function in your SAP system to make sure you are calling it correctly.  In my system, there are 4 required _Import_ parameters.  Additionally, any additional information about the call (successful or not) will be returned in the _Export_ parameter `RETURN` (BAPIRET2 structure).

I would take these steps:
1. Test/Execute the function module in `SE37` and find the appropriate _Import_ parameters and match these in your invocation.
2. Map the `RETURN` _Export_ parameter to a result class ,like in [this example](https://github.com/huysentruitw/SapNwRfc#call-function-with-input-and-output-parameters), so you can see any feedback on the call from SAP.

I hope this helps.

**Comment by saurabhsrivastava2009** [comment]
Hi @tom-j-irvine 
I'm new to SAP and not a native developer of SAP. My task is just to automate the job scheduling through c#. So pardon me if I make some terminology mistake.

When you say import parameters, does it mean the headers of the job table? like I have one JobName? If yes, I'll just try to get the actual name of the headers in the system and pass it through invoke.

**Comment by tom-j-irvine** [comment]
Before calling any function module in SAP, you have to understand how it works.  What sort of input and output does it require and provide, etc.  The bad news is that ABAP Function Modules (and ABAP in general) are typically not very intuitive, so you will have some work to do any time you want to map and call a new function.

For the function you are trying to call, this shows the _Import_ parameters - there are 5 total and only one of them is optional
![image](https://user-images.githubusercontent.com/66488893/215337674-1c91addd-c230-4773-9a40-b4793f82a080.png)

And, there is one _Export_ parameter (the return value) - the type of this parameter happens to be a structure (so, not a primitive value, but a multi-field structure).
![image](https://user-images.githubusercontent.com/66488893/215337768-b4a3bc17-fc3f-459c-92e8-826bc6b035b4.png)

Drilling in, you can see the fields of the structure
![image](https://user-images.githubusercontent.com/66488893/215337819-2fe68101-e596-46f8-9b85-63aca928905f.png)

Some other function modules may include _Changing_ and/or _Tables_ parameters as well (this one does not).

An example of how to map and call this function follows

```csharp
class StartJobParameters
{
    [SapName("JOBNAME")]
    public string JobName { get; set; }

    [SapName("JOBCOUNT")]
    public string JobCount { get; set; }

    [SapName("EXTERNAL_USER_NAME")]
    public string UserName { get; set; }

    [SapName("TARGET_SERVER")]
    public string TargetServer { get; set; }
}

class SapBapiReturn2
{
    [SapName("TYPE")]
    public string Type { get; set; }

    [SapName("ID")]
    public string Id{ get; set; }

    [SapName("NUMBER")]
    public string Number { get; set; }

    [SapName("MESSAGE")]
    public string Message { get; set; }

    // you could map other fields of the structure too, but if you don't, 
    // they just won't get deserialized in the response  
}

class StartJobResult
{
    [SapName("RETURN")]
    public SapBapiReturn2 JobResult { get; set; }
}

using var startJobFunction = connection.CreateFunction("BAPI_SOME_FUNCTION_NAME");
var result = startJobFunction.Invoke<StartJobResult>(new StartJobParameters
{
    JobName = "somejobname",   // I have no idea what parameter values are valid for what you are trying to do
    JobCount = "",
    UserName = "",
    TargetServer = ""
});

// after invoking, inspect the result to see what happened

```

**Comment by saurabhsrivastava2009** [comment]
Hi @tom-j-irvine 

Thank you for the explanation and because of this I'm able to perform _BAPI_XMI_LOGON_ and _BAPI_XBP_JOB_START_ASAP_ by creating the required parameter class, invoke and validate the result.
But now when I try to perform status operation _BAPI_XBP_JOB_STATUS_GET_, it throws the conversion error: _STATUS of type RFCTYPE_CHAR cannot be converted to type RFC_STRUCTURE_HANDLE_ .

I have followed the same mapping model as RETURN for this, but not sure on why it is not working. Can you have a look?
Here is the code for the same
```
public class SAPStatusOutputParameter
{
        [SapName("STATUS")]
        public SAPStatusOutputParamBAPI sapStatus { get; set; }
}

public class SAPStatusOutputParamBAPI
{
        [SapName("STATUS")]
        public string Status { get; set; }
}
```

**Comment by tom-j-irvine** [comment]
I think you are close, but are misinterpreting the export parameters
![image](https://user-images.githubusercontent.com/66488893/215616149-a9524562-8ed4-4237-b0b9-f12d78259f23.png)

The `STATUS` parameter is type `BAPIXMJOB-STATUS`, so while `BAPIXMJOB` is a structure, the parameter is typed based on the `STATUS` field of the structure.  It is the same sort of thing with the `HAS_CHILD` parameter.  So, I think your `SAPStatusOutputParameter` class should look something like this:

```csharp
public class SAPStatusOutputParameter
{
        [SapName("STATUS")]
        public string Status { get; set; }

        [SapName("RETURN")]
        public SAPStatusOutputReturnBAPI sapStatusOutputReturnBAPI { get; set; }

        [SapName("HAS_CHILD")]
        public string HasChild { get; set; }
}
```

**Comment by saurabhsrivastava2009** [comment]
Hi @tom-j-irvine 
Thanks, the suggestion given by you worked. But I do have a doubt on how to know which one is a string parameter and which one is a structure. Is it based on the value after the hypen(-)?

**Comment by tom-j-irvine** [comment]
I'm glad it worked for you.  However, I'm afraid you are going to have to learn a bit more about abap type declarations moving forward.  In this particular case, the declaration was pointing to a field of a structure (and the hyphen was a clue), but that isn't a universal rule you can follow.  In the future, you may see parameters that need to be mapped to other primitive types (see the [documentation](https://github.com/huysentruitw/SapNwRfc#input-and-output-mapping) for type mapping).  You may also see parameters that are mapped to table types (so, multi-column, multi-row structures).  None of this will be driven by a naming convention, but by drilling into the definition and understanding what it is.  There is lots of low-quality information about sap/abap online (most people think this knowledge should be hoarded for financial gain), but try to find information related to the abap dictionary to get a deeper understanding of the types of things these parameter may reference.

Finally, I assume there is an SAP person you are working with who is telling you which functions to call.  If so, can't they provide examples of how to call it with appropriate input/output?

**Comment by tom-j-irvine** [comment]
@saurabhsrivastava2009 - at this point, I'm hoping you will close this issue.  The software is working as designed.

**Comment by saurabhsrivastava2009** [comment]
@tom-j-irvine right, I agree with you! There is not much sap related documentation/information. 
Yes we can close this issue as it is working as designed. Thank you so much for this information.

And yes, I'm working with a SAP person and there are still some doubts related to file download remote BAPI, so working on it..

Thanks again :)
