### ISSUE TITLE
How do pass table parameters

### ISSUE THREAD

**Issue by basis100** [huysentruitw/SapNwRfc#79]
Dear huysentruitw:

thank your SapNwRfc Lib, I successfully completed a function call in server mode.

Now , I want to pass table parameters, What should I do ?

![image](https://user-images.githubusercontent.com/26346549/215657015-5b234f56-9833-40dd-80de-411bb0ba70bc.png)

**Comment by campersau** [comment]
Tables are just arrays, see https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table

```c#
using var fn = connection.CreateFunction("Z_STFC");
var result = fn.Invoke<StfcResult>(new StfcParameters
{
    SendId = "AAA",
    SendText = "SAP SEND THIS DATA",
    Makts = new[]
    {
        new Makt { Matnr = "9876432736749", Maktx = "this is a material" },
        new Makt { Matnr = "1222222211111", Maktx = "this is two material" },
        new Makt { Matnr = "3333333333333", Maktx = "this is three material" },
    }
});

class StfcParameters
{
    [SapName("SEND_ID")]
    public string SendId { get; set; }

    [SapName("SEND_TEXT")]
    public string SendText { get; set; }

    [SapName("MAKT")]
    public Makt[] Makts { get; set; }
}

class StfcResult
{
    [SapName("MAKT")]
    public Makt[] Makts { get; set; }
}

class Makt
{
    [SapName("MATNR")]
    public string Matnr { get; set; }

    [SapName("MAKTX")]
    public string Maktx { get; set; }
}

```

**Comment by hxshxs2011** [comment]
I used the campersau method with Tables as the input parameter, but still cannot succeed. Please provide guidance!

**Comment by hxshxs2011** [comment]
> Tables are just arrays, see https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table
> 
> ```cs
> using var fn = connection.CreateFunction("Z_STFC");
> var result = fn.Invoke<StfcResult>(new StfcParameters
> {
>     SendId = "AAA",
>     SendText = "SAP SEND THIS DATA",
>     Makts = new[]
>     {
>         new Makt { Matnr = "9876432736749", Maktx = "this is a material" },
>         new Makt { Matnr = "1222222211111", Maktx = "this is two material" },
>         new Makt { Matnr = "3333333333333", Maktx = "this is three material" },
>     }
> });
> 
> class StfcParameters
> {
>     [SapName("SEND_ID")]
>     public string SendId { get; set; }
> 
>     [SapName("SEND_TEXT")]
>     public string SendText { get; set; }
> 
>     [SapName("MAKT")]
>     public Makt[] Makts { get; set; }
> }
> 
> class StfcResult
> {
>     [SapName("MAKT")]
>     public Makt[] Makts { get; set; }
> }
> 
> class Makt
> {
>     [SapName("MATNR")]
>     public string Matnr { get; set; }
> 
>     [SapName("MAKTX")]
>     public string Maktx { get; set; }
> }
> ```
I used the campersau method with Tables as the input parameter, but still cannot succeed. Please provide guidance!

**Comment by basis100** [comment]
This is my blog about SapNwRfc :
https://basis.blog.csdn.net/article/details/128817975


whether You set sm59 in the blog's&nbsp; picture ?










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huysentruitw/SapNwRfc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 中午1:55
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [huysentruitw/SapNwRfc] How do pass table parameters (Issue #79)





  
Tables are just arrays, see https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table
 using var fn = connection.CreateFunction("Z_STFC"); var result = fn.Invoke<StfcResult&gt;(new StfcParameters {     SendId = "AAA",     SendText = "SAP SEND THIS DATA",     Makts = new[]     {         new Makt { Matnr = "9876432736749", Maktx = "this is a material" },         new Makt { Matnr = "1222222211111", Maktx = "this is two material" },         new Makt { Matnr = "3333333333333", Maktx = "this is three material" },     } }); class StfcParameters {     [SapName("SEND_ID")]     public string SendId { get; set; }     [SapName("SEND_TEXT")]     public string SendText { get; set; }     [SapName("MAKT")]     public Makt[] Makts { get; set; } } class StfcResult {     [SapName("MAKT")]     public Makt[] Makts { get; set; } } class Makt {     [SapName("MATNR")]     public string Matnr { get; set; }     [SapName("MAKTX")]     public string Maktx { get; set; } }
  
I used the campersau method with Tables as the input parameter, but still cannot succeed. Please provide guidance!
