### ISSUE TITLE
Unable to Read JOB Spool using RFC - BAPI_XBP_GET_SPOOL_AS_DAT

### ISSUE THREAD

**Issue by Kalyan7829** [huysentruitw/SapNwRfc#86]
Hello Team,

I have a requirement where i need to read the spool logs after executing the SAP job using RFC.

However I am getting the exception as  below
![image](https://user-images.githubusercontent.com/33179713/233998747-fa3e0e8c-f054-44ac-8c86-4b26a387c343.png)

C# code - 

Export Parameters
![image](https://user-images.githubusercontent.com/33179713/233999068-dc8c8d88-bac4-4b0d-b0d0-2a2c661c3a21.png)

Import Paramaters

![image](https://user-images.githubusercontent.com/33179713/233999245-75a9cb55-8d97-4bbb-bd91-90cae6f4693b.png)

Really not sure what datatype to be used to get the logs for the export parameter - SPOOL_LIST.

can you pls help me with this?

Thanks in Advance!

**Comment by tom-j-irvine** [comment]
You need to look at this part of the documentation:
https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table

In your function, the SPOOL_LIST is a table

Your import parameters look okay.  For export, assuming your SAPReturnBAPI class is defined correctly, that also looks okay.

For the SPOOL_LIST, I would do something like this (a similar question was answered here: https://github.com/huysentruitw/SapNwRfc/issues/58)

```csharp
public class SapJobDatSpoolExportParameters
{
    [SapName("SPOOL_LIST")]
    public SapSpoolListItem[] SpoolList { get; set; ) }
}

public class SapSpoolListItem
{
    [SapName("")]
    public string Value { get; set; }
}
```

**Comment by Kalyan7829** [comment]
@tom-j-irvine ,

Firstly Thankyou for the quick response.

The Solution you provided is working as per the requirement.
