### ISSUE TITLE
当我尝试将一个 RFCTYPE_TABLE 转为 IEnumerable<T> 时出现了异常，而数组并没有异常，这是为什么？

### ISSUE THREAD

**Issue by wangfei9999** [huysentruitw/SapNwRfc#88]
{"SAP RFC Error: RFC_CONVERSION_FAILURE with message: ET_OUT of type RFCTYPE_TABLE cannot be converted to type RFC_STRUCTURE_HANDLE"}

**Comment by RickGanKL** [comment]
It is a structure. You couldn't pass a table to a structure.

**Comment by RickGanKL** [comment]
你可以关闭这个Issue吗？ 我相信这个问题已经解决了.

**Comment by 13205090490** [comment]
How can I obtain RFCTYPE_ TABLE

data

**Comment by 13205090490** [comment]
ok。我已经知道如何获取数据了，感谢。
 类似
   public class TestOutputParameter : IRfcOutput
    {
        [RfcEntityProperty("RFCTYPE_TABLE")]
        public RFCTYPE_TABLE[]  data{ get; set; }
    }

    public class RFCTYPE_TABLE
    {
        [RfcEntityProperty("V1")]
        public string V1 { get; set; }

        [RfcEntityProperty("V2")]
        public string V2 { get; set; }
}

**Comment by tom-j-irvine** [comment]
https://github.com/huysentruitw/SapNwRfc#define-models-with-a-nested-table
