### ISSUE TITLE
How to auto clean *.trc files after Invoke function

### ISSUE THREAD

**Issue by IAmWhoAmI007** [huysentruitw/SapNwRfc#9]
Hi,
First thanks for your project.
This makes it easy for me to connect to the SAP interface to work, but there is a problem that has been bothering me, that is, every time I call the SAP interface, a .trc file is generated, which takes up space.
I would like to ask how to delete this file after calling it, or redirect this file instead of outputting it directly to the root directory

![image](https://user-images.githubusercontent.com/37363504/89761443-f55a6580-db20-11ea-974e-960487e1225e.png)

**Comment by huysentruitw** [comment]
This behavior is outside our control. It's the SAP binaries that write the trace logs to the current working directory, which is the csproj folder when debugging from Visual Studio.

There are several ways to work-around this:

- disable trace logging in the connection string (set TRACE=0)
- add the .trc to your .gitignore (if it botters you during working with git)
- add this to your csproj file to hide the files from the Solution Explorer
```
  <ItemGroup>
    <None Remove="*.trc" />
  </ItemGroup>
```

Let me know if this helps.

**Comment by IAmWhoAmI007** [comment]
Thinks,
I have tried the method you provided, now there is no **.trc** file.
By the way, this project is very nice.
