### ISSUE TITLE
RFC_CONVERSION_FAILURE with message: [My-table-return] of type RFCTYPE_TABLE cannot be converted to type RFC_STRUCTURE_HANDLE

### ISSUE THREAD

**Issue by GustavoDamasceno** [huysentruitw/SapNwRfc#99]
Hello,

I'm querying SAP using C# .NET Core, using sapnwrfc for the first time, and I'm encountering issues with querying an RFC. Essentially, I'm calling an RFC with two parameters and retrieving the result in table T_ZSDS_IH08A, but I'm getting the following error:

`SAP RFC Error: RFC_CONVERSION_FAILURE with message: T_ZSDS_IH08A of type RFCTYPE_TABLE cannot be converted to type RFC_STRUCTURE_HANDLE'`

Below is my code to access the RFC:

```
SapConfig sapConfig = new SapConfig();

string connectionString = sapConfig.SapconnectionString(ConfigurationManager.AppSettings["Ambiente"].ToString());
using var connection = new SapConnection(connectionString);
try
{
    connection.Connect();

    using var someFunction = connection.CreateFunction("ZRFC_IH08");
    var result = someFunction.Invoke<SapFunctionResult>(new SapFuncionParameters
    {
        EquipmentNumber = "",
        FunctionalLocation = "",
    });

}
catch (Exception ex)
{
    throw ex;
}

```

Below is my return class:

```
public class SapFunctionResult
{
    [SapName("T_ZSDS_IH08A")]
    public object table { get; set; }

}
```

My idea is to obtain the data from the table in result.table.

**Comment by GustavoDamasceno** [comment]
Using sapnco in the .NET Framework, I used 

`IRfcTable table = function.GetTable("T_ZSDS_IH08A");`

 to receive the data from the table.

**Comment by tom-j-irvine** [comment]
Take a look at this part of the documentation:
https://github.com/huysentruitw/SapNwRfc?tab=readme-ov-file#define-models-with-a-nested-table

You would follow a similar pattern where you have a separate class that defines the structure of the items in the table.  Then, in your `SapFunctionResult` class, the property to represent T_ZSDS_IH08A would be an array of those objects.  With that, you'll have a strongly typed C# array of objects in your result

**Comment by GustavoDamasceno** [comment]
I made it, thank you very much for the help!
